import './global.css';
import { UIProvider } from '@multisite-rice/ui';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
