import localFont from 'next/font/local';
import './global.css';
import { UIProvider } from '@multisite-rice/ui';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

const materialSymbols = localFont({
  src: '../../public/fonts/material-symbols-outlined.woff2',
  variable: '--font-material-symbols',
  weight: '100 700',
  display: 'block',
  fallback: ['sans-serif'],
  adjustFontFallback: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${materialSymbols.variable}`}>
      <body suppressHydrationWarning={true}>
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
